---
version: 2
jobs:
  build:
    docker:
      - image: philoserf/dockerlint
    steps:
      - checkout
      - run:
          command: find . -type f -name "Dockerfile" -exec dockerlint {} \;
workflows:
  version: 2
  build:
    jobs:
      - build
